name: Build AcquaOS ISO
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Tools & Build
        run: |
          # Qui siamo dentro un ambiente Arch Linux vero!
          pacman -Syu --noconfirm archiso git
          mkdir -p releng
          cp -r /usr/share/archiso/configs/releng/* releng/
          
          # Creiamo la lista pacchetti per AcquaOS
          echo "base linux linux-firmware cinnamon networkmanager sudo" > releng/packages.x86_64
          
          # Lanciamo la build
          mkdir -p output
          mkarchiso -v -w work_dir -o output releng/

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: AcquaOS-Crystal-ISO
          path: output/*.iso
