name: Build AcquaOS ISO
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Installa strumenti Arch
        run: |
          sudo apt-get update
          sudo apt-get install -y arch-install-scripts

      - name: Esecuzione build
          # Questo comando simula la creazione della ISO
        run: |
          chmod +x build_acquaos.sh
          ./build_acquaos.sh
          mkdir -p output
          echo "ISO Generata" > output/acquaos-crystal.iso

      - name: Carica la ISO
        uses: actions/upload-artifact@v4
        with:
          name: AcquaOS-ISO
          path: output/acquaos-crystal.iso
